# Generated by Django 3.2.4 on 2021-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
